### ISSUE TITLE
Update the Get started/Designing page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#107]
> As a Cupcake website designer

> I need to: update the "Get the kit" and "Start designing" section content on the Designing page page 

> so that: our adopters can find the correct information about "Get the kit" and "Start designing". 

#### Additional information

- The current cupcake Get started/Designing page can be viewed [here](https://carbon-for-ibm.netlify.com/getting-started/designing).

- We need to update the folder naming and path to the "Get the kit" and "Start designing".

#### Acceptance criteria
- [x] Updated content provided by @oliviaflory 
- [x] Content and design updated with markdowns.
- [ ] Content and design reviewed with Olivia and Wonil.

**Comment by oliviaflory** [comment]
Box note with copy updates started [here](https://ibm.ent.box.com/notes/570478708282)

**Comment by oliviaflory** [comment]
Ready for you to review the content @wonilsuhibm Jenny and Jacob will be updating this page in markdown so there is no design mock up.

**Updates have been made to:** 
File names, folder names and team names throughout the entire page based on our discussion last week

Added a section for explaining that our kits are for Sponsor adopters only right now, but to reach out to Linda if you'd like early access. Guessing you might have the most feedback on this section @wonilsuhibm 

A few smaller updates to content under the Anatomy sections.

Preview the [current page here](https://carbon-for-ibmdotcom.netlify.com/getting-started/designing/)
Box link to the [updated copy here](https://ibm.ent.box.com/notes/570478708282)

**Comment by JennySanchez** [comment]
Thank you, @oliviaflory.
@wonilsuhibm Let me know when I have your "good to go".

**Comment by JennySanchez** [comment]
@oliviaflory I checked with Wonil and I think we are good to go.

**Question:**
"If you are not a Sponsor Adopter and would like access to the kits to preview the components before they are officially released, please request access through `Github`."



For the `Github` link, is the "Design Kit access request" Git template created? I can link it to our Git repo issue template page for now if it's not ready but you might want to create a task issue for it.

**Comment by oliviaflory** [comment]
@JennySanchez  I just finished updating the copy, we ran our design kit name by Carbon team and ended up needing to make some changes.

The orange type indicates when the text should be set in the inline `code snippet` style.
I updated a few links

Let me know if you have any questions!

Link to [boxnote](https://ibm.ent.box.com/notes/570478708282)

> **Question:**
> "If you are not a Sponsor Adopter and would like access to the kits to preview the components before they are officially released, please request access through `Github`."
> 
> For the `Github` link, is the "Design Kit access request" Git template created? I can link it to our Git repo issue template page for now if it's not ready but you might want to create a task issue for it.

I just created the template to request access, and just need Wonil and Linda to review it, I will send you the link as soon as they can take a look!

**Comment by JennySanchez** [comment]
Sounds good, @oliviaflory !

**Comment by jacobottesen-dgc** [comment]
@oliviaflory Perfect. Thanks for all the help. I'll start adding this content to the page.

**Comment by oliviaflory** [comment]
Olivia to provide links for the following:
- [ ] Request access to design kit `Github` link
- [ ] Link to White design kit 
- [ ] Link to Gray design 90 kit
- [ ] Link to IBM.com library kit

**Comment by jacobottesen-dgc** [comment]
All updates have been made to the designing page. Just needs a few updates on links coming soon.

Live link: https://deploy-preview-193--carbon-for-ibmdotcom.netlify.com/getting-started/designing

cc. @JennySanchez @oliviaflory

**Comment by oliviaflory** [comment]
## Let's hold on these updates for now, posting here so I can remember them all and update when we finalize some of the naming


Found a few things I missed! Updated in the Boxnote, but also here: 

1. Link for [Github](https://github.com/carbon-design-system/carbon-for-ibm.com-design-kit/issues/new?assignees=ljcarot%2C+wonilsuhibm%2C+oliviaflory&labels=adopter+support&template=request-access.md&title=Design+kit+access+request)
<img width="709" alt="Screen Shot 2019-12-16 at 2 44 11 PM" src="https://user-images.githubusercontent.com/45692622/70937597-8c166700-2012-11ea-9cd9-12c79802069e.png">

---

2. Copy update for section 4, links in Boxnote: 
*The full IBM color pallet lives in the IBM Design Language library. The IBM icons live in the IBM Icons (16px, 20px)  library and IBM Icons (24, 32px) library.*
<img width="702" alt="Screen Shot 2019-12-16 at 2 46 31 PM" src="https://user-images.githubusercontent.com/45692622/70937764-e6172c80-2012-11ea-81ff-8526b6de0128.png">


Should the icons be the Sketch logo instead of the Bee because they are Sketch libraries?
<img width="764" alt="Screen Shot 2019-12-16 at 3 02 55 PM" src="https://user-images.githubusercontent.com/45692622/70938945-3d1e0100-2015-11ea-8a84-2ffa2bab3954.png">


---

3. Copy update: change "Carbon" to "IBM.com" anywhere I accidentally left Carbon under structure
 **Note** we may end up needing to update these names throughout the site once the `Carbon for IBM.com` vs `IBM.com Library | Carbon` debate is settled with Wonil, Mike and Matt.**
<img width="708" alt="Screen Shot 2019-12-16 at 2 50 53 PM" src="https://user-images.githubusercontent.com/45692622/70938205-bc123a00-2013-11ea-86fd-99daad26ff86.png">

---

4. This should be a list, similar to the typography structure section. 
<img width="704" alt="Screen Shot 2019-12-16 at 2 53 04 PM" src="https://user-images.githubusercontent.com/45692622/70938271-da783580-2013-11ea-807c-733967af54dd.png">
If the Gatsby template won't let you make it a list, remove the "–" dashes.

---

5. Support section 
Update "IBM.com components kits" to "IBM.com Library kits"
<img width="677" alt="Screen Shot 2019-12-16 at 2 55 35 PM" src="https://user-images.githubusercontent.com/45692622/70938446-317e0a80-2014-11ea-94f4-87ffa9c64b4a.png">

**Comment by oliviaflory** [comment]
ok @jacobottesen-dgc and @JennySanchez based on the naming decision from today (Dec 17) to name our website and respective products `IBM.com Library`  I've updated the Get started designing [Box Note](https://ibm.ent.box.com/notes/570478708282) to reflect all naming changes and link updates. 

I also caught a few things I missed in the first round of writing.

**All updates are in PURPLE** 💜 

Let me know if you have any questions

**Comment by oliviaflory** [comment]
@wonilsuhibm on this page we refer to our team as "Carbon for IBM.com team" we should decide if we want to update the name or leave it.

**Comment by oliviaflory** [comment]
@jacobottesen-dgc one more update, the folder has been renamed to: `IBM.com Library Design kit`

It will need to be updated on the website, marked it in Red within the Boxnote

**Comment by jacobottesen-dgc** [comment]
@oliviaflory I am getting broken links for the theme cards on the designing page. Do you have an updated link?

Designing page live: https://deploy-preview-213--ibm-dotcom-library.netlify.com/getting-started/designing

**Comment by jacobottesen-dgc** [comment]
@oliviaflory These links on the Get started designing page don't work. Do you know where we can get the correct links?

![Screen Shot 2019-12-19 at 9.40.00 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/dd376114-d66b-49a4-a162-d9809e2fc505)

cc. @JennySanchez

**Comment by JennySanchez** [comment]
Reached out to @jeffchew and @wonilsuhibm yesterday via Slack to find the links as well.

**Comment by wonilsuhibm** [comment]
This is the Box link: https://ibm.box.com/s/fdoqr1qb4agyoys5j8wo19eab60m4ek1

**Comment by JennySanchez** [comment]
Links updated and task completed.  All other Dev. related fix are recorded in the dev fix issue #63.
