### ISSUE TITLE
Update the Components/Masthead page content

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#152]
> As a Cupcake website designer

> I need to: update the on the Masthead page content

> so that: our adopters can find the most up to date information about Masthead. 

#### Additional information

The current cupcake Component/Masthead page can be viewed [here](https://carbon-for-ibmdotcom.netlify.com/components/masthead).

We need to update:
1. All the images on the page.
2. Add labels to all L0 and L1 variations.

#### Acceptance criteria
- [x] @larahanlon2 provides the list of the L0 and L1 variations and updated images we need for the page update.
- [ ] Content and design updated with markdowns.
- [ ] Content and design reviewed by Wonil.

**Comment by larahanlon2** [comment]
Provided Jenny and Jacob with the following updated visuals:
– L0 variations
– L1 variations
– L0-L1 breakpoints
– L0-L1 anatomy

Sketch file can be found [here](https://ibm.box.com/s/ruhfsfxtafa15cr1iu25qrvzno6qesgm).

**Comment by JennySanchez** [comment]
Image updates for the [Masthead page](https://deploy-preview-182--carbon-for-ibmdotcom.netlify.com/components/masthead) based on the conversation with Lara today:

For L0 and L1:
![Screen Shot 2019-12-12 at 11 34 19 AM](https://user-images.githubusercontent.com/45213839/70738976-6ff58b80-1cdb-11ea-974f-a2325f43ca74.png)

For the Behaviors:
![Screen Shot 2019-12-12 at 11 41 13 AM](https://user-images.githubusercontent.com/45213839/70739032-8c91c380-1cdb-11ea-8482-75b125c09368.png)

@jacobottesen-dgc I will send the image Sketch file to you via Slack.

**Comment by JennySanchez** [comment]
All updates are done and the page can be viewed [here](https://carbon-for-ibmdotcom.netlify.com/components/masthead).

**Comment by larahanlon2** [comment]
@JennySanchez @jacobottesen-dgc 

@oliviaflory and I reviewed the masthead page. Take a look at suggestions/changes below and let us know if all is doable. Thanks!
...
**Section:** Titles
**Content:** Never use a logo and/or image for the title.
**Change:** Please move this last bullet point to its own line as this applies to both L0 and L1

—

**Section:** Nav Labels 
**Change 01:** Please update the section title to "Nav link labels"
**Change 02:** Please update the entire paragraph to the following:

These labels are short descriptors to inform the user what type of content they will find. Keep labels preferably to one word or a maximum of 20 characters in all languages, but two words are supported if necessary. Never use the name of a product, service, document, or event for labels. These labels should not link to non-IBM sites, or be used as anchor tags to page content. Avoid using IBM proprietary terminology or “inside” language. 

—
**Section:** CTA (call to action)
**Change:** Please remove entire section because the current masthead is not supporting CTA's. We could add this content to a new Git issue and put it in icebox for future updates.

—

**Section:** Navigation
**Content:** First two bullet points for L0 and L1
**Change:** Please change *nav labels* to *nav links*
Remove supports icons??

**Content:** Supports icons
**Change:** Please replace with *Supports search and profile services*

**Content:** Uses a selection bar to inform the user where they are currently within the overall navigation.
**Change:** Please update this last bullet point with *The masthead navigation informs the user of their location at all levels.* 

**Content:** Once there is not enough space to accommodate a label(s) within the L0 or L1, an overflow menu (ellipses icon) will appear as the last label able to fit within the given space. This “more” menu supports a drop-down list with the overflow label(s). 

**Change:** Please update the entire paragraph with *Once there is not enough space to accommodate L0 and L1 nav links, a hamburger menu will appear to house all nav links.*

—

**Section:** L1 eyebrow
**Change:** Because the L1 is currently not available we need to add a note, similar to the CTA section. Suggested addition:

*Note: The masthead L1 is not currently available for adoption. Please see the Release Schedule pinned on our Github for detail.*

—

**Section:** Behavior
**Change:* Apply same naming to L0 & L1 nav links vs labels. Change “header links” to "nav links"

**Content:** Image of responsive sizes
**Change:** L1 title chip in mobile image “get started” should have selected/active blue underline state. See the Sketch file.

**Addition:** Please add the following paragraph: *The masthead is sticky when scrolling. If there is only an L0, the L0 sticks to the top of the browser. When there is an L0 and L1, the L1 collapses to 48px tall and sticks to the top or the browser.*

—

**Section:** Rules
**Change:** Please remove entire section

—

**Comment by JennySanchez** [comment]
Jacob and I take a look at the edits and we are good to make updates. If we have questions, we will reach out.

**Comment by JennySanchez** [comment]
This task is completed. Items need to be fixed are recorded in the dev fix issue #63.
