### ISSUE TITLE
Screen resolution guidelines

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library-website#20]
### User story
As a designer of IBM.com experience, I need to know recommended art board sizes that will help design pages and experiences that can be used in real life situations.

### Notes
- This story is to create recommended art board sizes to be published for designers.
- This story will most likely be converted to an epic with smaller stories to achieve the acceptance criteria.

### Acceptance criteria
- Recommended art board sizes have been identified based on average screen sizes and available screen real estate after operating system tool bars and browser tool bars have been taken into consideration.

### Additional information
- For monitor resolution stats: https://gs.statcounter.com/screen-resolution-stats
- Early studies by Wonil: https://ibm.box.com/s/i9r5ra9euhcuvqikkp2nfopn0tdfu15l

**Comment by RobertaJHahn** [comment]
The guidelines work has been deferred until resources are available.  The design kit and components will continue.

**Comment by wonilsuhibm** [comment]
@larahanlon2 @JennySanchez @oliviaflory @jacobottesen-dgc please review and comment.

**Comment by larahanlon2** [comment]
One of the Security designers reached out to me before the holidays about artboard/grid sizes. She does a lot of web and app work for events and showcases...where the displays are large. She and her dev had to hack the designs/code so they looked good on displays larger than 1584px. **Do you think we (or Carbon) should incorporate super large artboards and grids?**

Part of our conversation:
_All my work is for iMac (2048x1152px) so even max expressive type can look small on it while Carbon components – like buttons – look TINY (edited) 
it seems like all the existing Carbon stuff is for low res PC’s
I feel like we’ve had issues with responsiveness in the past too because Apple resolutions are so high but the physical screen size might be quite small in reality._

**Comment by wonilsuhibm** [comment]
Strictly speaking. that falls under events / environmental design and 's outside of our scope. I'd suggest connecting her with Pete Garvin from Brand team, he has done studies and guidelines for grid and layout for all media.

**Comment by JennySanchez** [comment]
@wonilsuhibm The sizes list looks good to me. Most of the design files from the brand team I have seen are designed with the same desktop sizes you have on the list already, so I think you are spot on.

A side note, last year, Googled announced they are going to use the mobile-first indexing as the default. So if our pages want to be found, the mobile version should be focused on even most of our users probably are on the desktop while browsing through IBM.com for IBM services or offerings.

**Comment by wonilsuhibm** [comment]
I think we can get by by making sure that our patterns and components are mobile fully responsive.
