### ISSUE TITLE
Review the "content order structure" for the Components and Layout patterns sections

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#229]
> As a cupcake website content creator

> I need to make sure the content order for the pages under the Components and Layout patterns are easy to read and make sense to the adopters

> So that our adopters can consume the information efficiently.

#### Additional information

(Feedback from Wonil)
The current content structure doesn't make much sense to me. I completely understand that we are following Carbon template, but the current structure where the description of the two versions is separate from the visuals is really throwing me off, and is a bad user experience.

(The content order structure suggested by Wonil)
1. Intro copy
2. Default footer
   - Title: `Default footer`
   - Description: `
   - Visual
   - Anatomy
3. Minimal footer
   - Title: `Minimal footer`
   - Description
   - Visual
4. Rules

#### Acceptance criteria
- [ ] Get adopter feedback and decide the structure for update.
- [ ] Share the outcome with Jan/Carbon to get input.
- [ ] Create task issue for the update task.

**Comment by JennySanchez** [comment]
FYI - @wonilsuhibm

**Comment by larahanlon2** [comment]
I can understand the feedback for `footer` as there is not that much content. @JennySanchez is the idea to show an overview of the entire component/pattern at the top so that adopters can, at a glance, see everything that is included? If so, the current way makes more sense. Especially when there is a lot of content because users have to scroll so far to see the different examples.

For `lead space` I added the **types** table near the top so people. Would something like this help for components too? Then you can implement Wonil's suggestion. 

So it would be:

1. Intro copy
2. Types (table list)
3. Default footer

- Title: Default footer
- Description: `
- Visual
- Anatomy

4 Minimal footer

- Title: Minimal footer
- Description
- Visual

5. Rules

**Comment by JennySanchez** [comment]
@larahanlon2 You are correct - the idea is to show an overview of the entire component/pattern at the top so that adopters can, at a glance, see everything that is included.

If we follow the same format, for Lead Space, it will have Intro, then the entire component/pattern at the top, then we dive into types.

I will set up a time for us to take a look all together before we make any changes. Sounds good?

**Comment by JennySanchez** [comment]
Review meeting set up for 01/07 Tuesday.

**Comment by JennySanchez** [comment]
Based on the discussion today, we will make updates listed below to the Footer, Masthead, and Lead Space pages.

- [ ] Move the description under each component and layout pattern title.
- [ ] Update section title from "Documentation" to "Developer Documentation".
- [ ] Remove the "Types" section.

---

Additionally, @oliviaflory will share her exploration of the Component content structure she has. We will take a look and go from there for additional edits we might do to make the page content structure better for adopter experience.

**Comment by JennySanchez** [comment]
Update completed and can be viewed on the live website.
