### ISSUE TITLE
components overview image switches to low-res. See carbon overview page

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/ibm-dotcom-library-website#256]
current (lores)
<img width="1193" alt="Screen Shot 2019-12-31 at 5 15 15 PM" src="https://user-images.githubusercontent.com/32881239/71636089-31bffd80-2bf1-11ea-8811-b5dbd53d012c.png">

too much compression. Also assume svg will be better and my hunch is Carbon site is svg.

**Comment by JennySanchez** [comment]
@jeffchew Can you tell me the steps and how many story points our dev team might need in order to create and link each card to its own components pages on the Carbon website?

ps: You might want to look into how the images were pulled into the [Carbon components page](https://www.carbondesignsystem.com/components/overview).
