### ISSUE TITLE
Research rules for title & subtitles on resource cards

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library-website#285]
> As a cupcake website content creator

> I need to find out resource card titles and subtitles ruling

> So that I can make sure our website content is 100% aligned with the Carbon website.

### Tasks
- [x] Meeting with Carbon to learn the best practices and rules for setting up titling on resource cards.

#### Acceptance 
- [x] Create a task issue to update the resource card title treatment.

**Comment by jacobottesen-dgc** [comment]
cc. @JennySanchez 

Meeting with Connor from Carbon 01/16 today.

**Comment by jacobottesen-dgc** [comment]
cc. @JennySanchez 

- Meeting with Connor from Carbon 01/16 today. 
- Sent Connor a proposal for titling rules on resource cards.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Can you share the outcome of the best practices and rules study here? Please also share your recommendation for us to follow for our website.

**Comment by jacobottesen-dgc** [comment]
cc. @JennySanchez 

Jenny and I showed the Carbon team our proposals for the resource card titles. They said they would look in to it. I sent the following files below to Connor on Carbon. 

Current titles:
![Screen Shot 2020-01-24 at 9.10.10 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/7cf308be-0e0e-41b3-8dc2-3a12cf43fe97)

Proposal #1
![Screen Shot 2020-01-24 at 9.10.15 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/fcc57141-4e41-4a5e-ab20-974d81cc952f)

Proposal #2
![Screen Shot 2020-01-24 at 9.10.20 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/0a5e6ae4-782c-4b08-be2a-81e1aa96f814)

**Comment by JennySanchez** [comment]
@wonilsuhibm @larahanlon2 @oliviaflory Thoughts on the proposal listed above?

**Comment by oliviaflory** [comment]
cc @jacobottesen-dgc @JennySanchez 

I lean towards `Proposal #1` because we are still hosting our IBM.com library and theme libraries kits on Box and we **do not** want users to "Download" those files. We need them to add those files as libraries through Sketch, otherwise they won't receive our automatic updates. 
I wonder if it's considered "Download" when you add them via Sketch cloud on the Carbon site either, possibly "Install" works better?

In`Proposal #2` I worry that the word "Download" might be slightly misleading to our users.

**Comment by JennySanchez** [comment]
Agreed with you, @oliviaflory!

**Comment by larahanlon2** [comment]
I also like `proposal #1`. I like the helpful, conversational language. 

One thought: I would still use the **download** icon for anything that is a direct download (instead of all cards having the **launch** icon). Unless of course, if they are all the same i.e launch a new tab/destination then it's fine to use the same icon on all cards!

**Comment by JennySanchez** [comment]
Great. We will move froward with proposal #1. The next step task will be recorded via #308.
