### ISSUE TITLE
Add the IBM.com shell template link to the website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#290]
We will add the the IBM.com shell template link to the website as a Resource Card.

We will add the card to Get Started/Designing page.
https://ibm-dotcom-library.mybluemix.net/getting-started/designing

We will add the card to the Resource Page "Color, grid, and icons" section.
https://ibm-dotcom-library.mybluemix.net/resources

**Comment by JennySanchez** [comment]
@oliviaflory Can you share the link and recommendation on where the IBM.com shell template link should be added on the Get Started/Designing page? Thank you.
https://ibm-dotcom-library.mybluemix.net/getting-started/designing

**Comment by oliviaflory** [comment]
It's the same link as the White and Gray 90 theme design kits, https://ibm.ent.box.com/folder/90951802351

I don't think we need the link to the UI shell template on the Get started / Designing page because it's one that you will download and save as a template like the IBM Grid template. We don't have the link to the grid template on this page either. 


I wonder if we need to find a place on the resources page for the IBM.com Library design kit (the one with the masthead and footer). Should that be a new issue?

**Comment by JennySanchez** [comment]
Based on the discussion, there are three items we need to do for this task:
- Get started/Designing page "Get the kit" section step 3, update the name of the design kit from IBM.com design kit to IBM.com library design kit.
- Resources page, add the "IBM.co Shell template" resource card under the "Color, grid, and icons" section.
- Resources page, add "IBM.com library components" section tile below the Theme libraries section and add the "Component design kit" resource card under it.

**Comment by JennySanchez** [comment]
Hi @oliviaflory The updates are completed and you can view it on the staging site [here](https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/294/resources). Let me know if I missed anything.

**Comment by oliviaflory** [comment]
Thank you @JennySanchez it all looks great, but one slight adjustment: 

I think we need to change the link for the IBM.com library card to direct to the box **folder** rather than the IBM.com Library **file** because the first thing Box says is to "download the file" and we don't want people downloading the library file.

Folder:
<img width="1372" alt="Screen Shot 2020-01-23 at 2 55 50 PM" src="https://user-images.githubusercontent.com/45692622/73018926-8cafd380-3df0-11ea-886f-dbfd63568f85.png">


File:
<img width="1372" alt="Screen Shot 2020-01-23 at 2 55 46 PM" src="https://user-images.githubusercontent.com/45692622/73018931-8e799700-3df0-11ea-80e6-e8104eec99bd.png">

**Comment by wonilsuhibm** [comment]
@JennySanchez I feel that this IBM.com shell template could belong to the IBM.com library section. What do you think?

**Comment by oliviaflory** [comment]
> @JennySanchez I feel that this IBM.com shell template could belong to the IBM.com library section. What do you think?

@wonilsuhibm I asked Jenny to add the Shell template under the Grids and icons section.
1. Because that's where the UI Shell is in the Carbon site.
2. Because we didn't have the IBM.com Library section in resources yet.

Since the Shell is part of our offering, moving it to the IBM.com Library section is OK with me. Let's hear what Jenny and Jacob think.

**Comment by JennySanchez** [comment]
@wonilsuhibm @oliviaflory I can see it go both ways. Since we have IBM.com Library section now, I think we can move all IBM.com's specific resources under the IBM.com Library section.

**Comment by oliviaflory** [comment]
> I think we need to change the link for the IBM.com library card to direct to the box **folder** rather than the IBM.com Library **file** because the first thing Box says is to "download the file" and we don't want people downloading the library file.

Thank you @JennySanchez for pointing out that directing the link to the folder might make adopters confused as to which file is the right one because the file name "IBM.com Library" and card title "Components design kit" are not the same.

Here are my two suggestions:
1. Use the exact file name "IBM.com Library", like we do in the other resource cards so it is clear to adopters which file to add as a library. This is slightly weird because it is the same as the section name.
<img width="1131" alt="Screen Shot 2020-01-24 at 11 52 59 AM" src="https://user-images.githubusercontent.com/45692622/73087512-998c0000-3ea0-11ea-9073-a7afdb79e623.png">

2. Use "IBM.com Library (components)" as the card title, this indicates that it is the component version of the IBM.com library and is close to the file name.
<img width="1128" alt="Screen Shot 2020-01-24 at 11 53 13 AM" src="https://user-images.githubusercontent.com/45692622/73087637-d22bd980-3ea0-11ea-8e85-6609a2649328.png">

**Comment by JennySanchez** [comment]
@oliviaflory I like option 2 and will make the updates.

**Comment by JennySanchez** [comment]
@jeffchew We need help with the PR since the changes did not pass the checks.

**Comment by JennySanchez** [comment]
@jeffchew Thank you for your help.

Updates completed and can be viewed [here](http://ibm-dotcom-library.mybluemix.net/resources/).
