### ISSUE TITLE
Update overall website content publishing process

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#322]
> As a Cupcake website creator

> I need to share how the website page content crafting process and steps are

> so that I can: use it for alignment with our team members and set proper expectation.

####Task

- [x] Jenny to work on the general process and 

#### Acceptance criteria

- [x] Have the process ready to share with the team.

**Comment by JennySanchez** [comment]
**Task follow-up:** Sing up for the squad huddle on Thursday to get feedback.

**Comment by JennySanchez** [comment]
@larahanlon2 @oliviaflory @wonilsuhibm Can you take a look and let me know what do you think?

FYI: I will share the detail with the whole team in our huddle on 03/19.

**Comment by wonilsuhibm** [comment]
This process looks good to me. Thank you @JennySanchez

**Comment by oliviaflory** [comment]
@JennySanchez thanks for sending over, this process makes sense to me. 

One suggestion: if any or all of the tasks depend on the previous ones being completed, it might be good to note which half of the sprint something needs to be accomplished. 
For example in Sprint 2
Create draft design mock up needs to be done in the first half of the sprint so the review, updates and share to Carbon can happen in the second half.

This might help keep the process moving and not get off track in the sprint because it does seem a little tight if everything is dependent on the previous step. Especially if you and Jacob aren't the only one creating the content :)

**Comment by larahanlon2** [comment]
Looking good @JennySanchez ! The only tiny thing I would add is, for the _produce supporting assets_ step, the visual/ux designer doing this may need to work with the designer of the pattern to either create or review the assets to ensure they are accurate. Just something to note rather than an additional step, I think.

**Comment by JennySanchez** [comment]
Thank you all for the input. Document updated and ready to share with the team.
