### ISSUE TITLE
Content Publishing - Beta (01 Card Section and 02 Feature Card)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#499]
#### Objective:
Go over the publishing process in place (As-Is) and spot the opportunity for improvement.

#### Goal:

- Page to be published: Card section and Feature Card patterns

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Based on the discussion I had with Wonil and Lara. Card Section and Feature Card patterns are the two patterns for us to start the content crafting process.

I will take the Card Section pattern and you will focus on the Feature Card pattern. Let me know if you have any questions and the MVP content template can be downloaded here.

**Comment by JennySanchez** [comment]
@RobertaJHahn I took Jacob off the task as discussed in the planning meeting that this might happen since he has a full sprint load of tasks to wrap up. I am working on both page content crafting now - FYI.

**Comment by JennySanchez** [comment]
@wonilsuhibm @larahanlon2 
Below are the two pattern pages - Card Section and Feature Card Block.

Can you please take a look and let me know if anything is missing or edits needed?

- Card Section work file can be found [here](https://ibm.box.com/s/e6zrghpleagprc11wg6qa9v1x10biuor).
- Feature Card Block work file can be found [here](https://ibm.box.com/s/eaik3m5sq0sgk5r1b9178snma5l59opu).


![Pattern - Card section.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/a5b7c0f4-ac57-4c28-a514-600e97d69ae7)
![Pattern - Feature card block.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/c954981f-2f32-4a60-9e9e-05c225f56b15)

**Comment by larahanlon2** [comment]
Hey @JennySanchez thank you! Looking good! 

## Cards
I notice in your file that the cards are all white on white background. Can I ask where you pulled those designs from? I ask because what you have does not correctly map to the Carbon theme settings. By default, though, all cards should be gray 10 on a white background. Like this:

**Card section simple: white theme** (default)
<img width="1447" alt="Screen Shot 2020-07-13 at 10 54 09 AM" src="https://user-images.githubusercontent.com/53093550/87319867-35193780-c4f8-11ea-8832-2a3bc50d1ad5.png">

If you are showing white cards then the background should be gray 10. Like this:  

**Card section simple: gray 10 theme**
<img width="1449" alt="Screen Shot 2020-07-13 at 10 54 21 AM" src="https://user-images.githubusercontent.com/53093550/87319547-c3d98480-c4f7-11ea-9ad4-c2daf86897fb.png">


Check out the [Carbon theme knob on Storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sections-cardsectionsimple--default) to see how the themes apply.

👉 This is the same for the **card section with images** – by default the cards should be gray 10 on a white background. Not white on white.

_
_
_

## Feature card block
For **feature card block medium**, the heading is missing from the layout. The image that you are showing is more like the component itself: feature card. The pattern in our Storybook and design includes the heading (this is what sets it apart from the component and why it's called a `block`). See the heading here:
<img width="805" alt="Screen Shot 2020-07-13 at 10 48 02 AM" src="https://user-images.githubusercontent.com/53093550/87323190-70b60080-c4fc-11ea-8d5b-68aafade4853.png">

**Comment by larahanlon2** [comment]
Another thought. @JennySanchez I still find it odd that some of the cards have real content, some have lorem ipsum (or a mix).

**Comment by JennySanchez** [comment]
Hey @larahanlon2 The images are from the Visual spec files (see links below). Wonil and I had a conversation and he pointed out the example in Storybook might not reflect exactly how it should look like so it will be better for me to pull elements from the visual spec file for the image creation. 

For Card section simple: https://ibm.box.com/s/6prfrgt7dftdg47ejy3q3m4x7h47kbmo
For Card section with images: https://ibm.box.com/s/u4acyo9oeqya8xidimxtidh8k8y08fza
For Feature card block medium: https://ibm.box.com/s/pasipprq3njaholcg9bgtnv7khzq4kkq
For Feature card block large: https://ibm.box.com/s/fort8v1pj93z0ax6zgipcu0mbxsuwry1

---

For the Card, about the background color, since our website page background is in Gray 10, that's why I keep the background in white for all the examples so it can show properly. Maybe I should show the cards in Gray 10 instead.

Agreed on the mixture of lorem ipsum or actual content looks weird, let me create some content for it.

---
For the Feature card block, I will add the heading.

**Comment by larahanlon2** [comment]
Thanks @JennySanchez ! Yep, pulling from the visual specs makes sense and is a good idea. If you look at the specs, though, you'll notice that the cards are always either white on gray 10 background or gray 10 on white background. In your mockup, all of the cards are white on white which is incorrect. See below:

**This is what I see from your design:**
<img width="1118" alt="Screen Shot 2020-07-15 at 10 10 05 AM" src="https://user-images.githubusercontent.com/53093550/87555512-8d307500-c683-11ea-9618-6c2785782d2f.png">

**This is what it should be:**
<img width="811" alt="Screen Shot 2020-07-15 at 10 10 49 AM" src="https://user-images.githubusercontent.com/53093550/87555553-99b4cd80-c683-11ea-88a8-a38423a8314e.png">

**Comment by JennySanchez** [comment]
@larahanlon2 The discussion we had earlier today helps a lot. Thank you.

**Comment by JennySanchez** [comment]
**Updated design:**

![Pattern - Card section V2 - Ready](https://user-images.githubusercontent.com/45213839/87589400-cb8d5a80-c6aa-11ea-8a11-94da26861e6d.jpg)
![Pattern - Feature card block V2 - Ready](https://user-images.githubusercontent.com/45213839/87589404-ccbe8780-c6aa-11ea-90f9-c0e7f9010445.jpg)
